### ISSUE TITLE
TypeError: print_summary() got multiple values for argument 'add_string'

### ISSUE THREAD

**Issue by DaWe35** [DaWe35/Binance-websocket-api-to-mysql#6]
```
13:19:00 | Inserted rows: 16,444,850 | Last sec insert: 311 | Avg insert/s: 343 | sql queries: 163495
Traceback (most recent call last):
  File "/home/ether/.local/lib/python3.6/site-packages/unicorn_binance_websocket_api/unicorn_binance_websocket_api_manager.py", line 2223, in print_summary
    temp_stream_list = copy.deepcopy(self.stream_list)
  File "/usr/lib/python3.6/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.6/copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib/python3.6/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.6/copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib/python3.6/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.6/copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib/python3.6/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.6/copy.py", line 239, in _deepcopy_dict
    for key, value in x.items():
RuntimeError: dictionary changed size during iteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "Market_logger.py", line 261, in <module>
    binance_websocket_api_manager.print_summary(add_string=your_text)
  File "/home/ether/.local/lib/python3.6/site-packages/unicorn_binance_websocket_api/unicorn_binance_websocket_api_manager.py", line 2225, in print_summary
    result = self.print_summary(self, add_string=add_string, disable_print=disable_print)
TypeError: print_summary() got multiple values for argument 'add_string'

```

**Comment by DaWe35** [comment]
```
4:13:06 | Inserted rows: 5,984,600 | Last sec insert: 397 | Avg insert/s: 394 | sql queries: 59399
Traceback (most recent call last):
  File "/home/ether/.local/lib/python3.6/site-packages/unicorn_binance_websocket_api/unicorn_binance_websocket_api_manager.py", line 2223, in print_summary
    temp_stream_list = copy.deepcopy(self.stream_list)
  File "/usr/lib/python3.6/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.6/copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib/python3.6/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.6/copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib/python3.6/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.6/copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib/python3.6/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.6/copy.py", line 239, in _deepcopy_dict
    for key, value in x.items():
RuntimeError: dictionary changed size during iteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "Market_logger.py", line 260, in <module>
    binance_websocket_api_manager.print_summary(add_string=your_text)
  File "/home/ether/.local/lib/python3.6/site-packages/unicorn_binance_websocket_api/unicorn_binance_websocket_api_manager.py", line 2225, in print_summary
    result = self.print_summary(self, add_string=add_string, disable_print=disable_print)
TypeError: print_summary() got multiple values for argument 'add_string'

```
